# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 雜文宅
email: baichr8@gmail.com
copyright: 白崇容
description: >-
  白崇容的小博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.baichr.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:year-:month-:day-:title

collections:
  category:
    output: true

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: page
      excerpt_separator: <!--more-->
  -
    scope:
      path: "pages"
    values:
      layout: page
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

social-media:
  - {class: 'fas fa-envelope', link: 'mailto:baichr8@gmail.com', name: 'Email'}
  - {class: 'fas fa-rss-square', link: '/feed.xml', name: 'RSS feed'}
  - {class: 'fab fa-twitter', link: 'http://twitter.com/baichro', name: 'Twitter'}

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

sass:
  style: :compressed

paginate: 10
paginate_path: "/page/:num/"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# theme: jekyll-theme-dinky

category_url_mapping:
  - {category: '新手作者', url: 'writing'}
  - {category: 'English', url: 'english'}
  - {category: '乱七八糟的想法', url: 'thoughts'}
