# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 破道诗
subtitle: 路不在脚下，而在人心
email: wsroseanne@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  破道诗官方网站
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wroseanne.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:year-:month-:day-:title
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
      categories: posts
      excerpt_separator: <!--more-->
  -
    scope:
      path: "pages"
    values:
      layout: page

social-media:
  - {class: 'fas fa-envelope', link: 'mailto:wsroseanne@gmail.com'}
  - {class: 'fas fa-rss-square', link: '/feed.xml'}
  - {class: 'fab fa-twitter', link: 'http://twitter.com/prosrose'}

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

sass:
  style: :compressed

paginate: 5
paginate_path: "/page/:num/"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# theme: jekyll-theme-dinky
